### ISSUE TITLE
Native file picker not used

### ISSUE THREAD

**Issue by Miepee** [Naii-the-Baf/rdv-spoiler-log-parser#20]
For some reason it uses the weird qt provided filepicker and I'm not quite sure why

**Comment by Miepee** [comment]
AFAIK the qt documentation does state that the first case should work tho?
But I could also be misremembering

**Comment by Naii-the-Baf** [comment]
The Qt documentation mentions that the native filepicker is used unless the class used is a subclass of QFileDialog containing the Q_OBJECT macro, in which case the Qt filepicker is used. Using QFileDialog.getOpenFileName is one such case.
