### ISSUE TITLE
functionnames use PascalCase instead of snake_case

### ISSUE THREAD

**Issue by Miepee** [Naii-the-Baf/rdv-spoiler-log-parser#23]
python style guide

**Comment by Naii-the-Baf** [comment]
I suppose you mean they should be snake_case instead of PascalCase? The function names are in PascalCase.

**Comment by Miepee** [comment]
Yes.
The issue title literally is "functions use pascalcase" not "functions should use pascalcase" :P

**Comment by Naii-the-Baf** [comment]
Ah whoops I can't read
